global using FluentAssertions;
global using TechTalk.SpecFlow;
global using TechTalk.SpecFlow.Assist;
global using ProductAPI.Data;
global using ProductAPI.Models;
global using ProductUIAutomationBDDTests.Pages;
global using WebUIAutomationTestFramework.Driver;
global using WebUIAutomationTestFramework.Extensions;
global using OpenQA.Selenium;