name: E2E UI Tests CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build the script file
      run: |
        echo --- Running Tests ---
        sh ./Scripts/run.sh
    - name: Publish report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: SpecFlowReport
        path: ./reports
    - name: Deploy SpecFlow LivingDoc report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports